### ISSUE TITLE
Cannot plot from different datatypes on the same figure

### ISSUE THREAD

**Issue by ADCollard** [danholdaway/eva#101]
As I understand it the format for the EVA yaml files is as below:

```
diagnostics:
- data:
    type: IodaObsSpace
 
  transforms:

  graphics:

- data:
   type: GsiObsSpace
 
  transforms:

  graphics:
```

I.e., the type, transforms and graphics are all under the `data` header and so you cannot have a figure produced that includes data from both `IodaObsSpace` and `GsiObsSpace`

This is something that would be desirable.
