### ISSUE TITLE
Modify IodaObsSpace.py to issue a warning if input file isn't found

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [danholdaway/eva#221]
## Description

Modify `IodaObsSpace.py` to issue only a warning if the requested IODA data file is not found.  Presently a file not found is a fatal error.  Missing data files are fairly common occurrences in the DA monitor usage, so this behavior needs to be changed.

## Acceptance Criteria (Definition of Done)

Requested IODA data file(s) that are missing produce a warning message and processing continues as able. 

## Dependencies

None

**Comment by Dooruk** [comment]
@EdwardSafford-NOAA I noticed you are dealing with timeseries, which I also started experimenting with. I have to repeat the datasets section (below) for however many cycles there are for each observer. I was wondering if there is a better way of doing this or there has to be a new functionality added to the timeseries class somehow?

```yaml
datasets:
  - name: experiment
    type: IodaObsSpace
    filenames:
    - ./PT6H/2021-07-08/ncdiag.fgat_jra55_01.ob.PT6H.sst_viirs_n20_l3u.2021-07-08T21:00:00Z.nc4

    groups:
    - name: ObsValue
      variables:
      - seaSurfaceTemperature
```

**Comment by EdwardSafford-NOAA** [comment]
@Dooruk Yes repeating the datasets section for each file is an awkward construction in my mind.  We use an extended form of jinja (from wxflow repo) to substitute/expand the input yaml file we're sending to eva.  Reproducing the datasets section for each file is probably doable dynamically but it's going to be more work than seems necessary.

When I added `MonDataSpace` (which supports ingest of legacy DA monitor data) to eva, I allowed the input yaml file to simply list as many filenames within the same group as desired.  That makes the jinja substitution pretty straightforward.

One other thing I'm running into is that I need a time series of the number of observations in various QC categories across n data files (~120 usually).  At present time_series can only perform `sum` and `mean` functions.  I need a way to simply `count`.  I could get around this by modifying `IodaDataSpace` to determine the counts and then add that to the dataset as a variable, but it might make more sense to do this in time_series so it would apply to other data objects besides `iodaDataSpace.`

It might be useful to ask @CoryMartin-NOAA  and @kevindougherty-noaa for their thoughts on this.

**Comment by CoryMartin-NOAA** [comment]
Does specifying multiple filenames not work? Or does that not properly distinguish between analysis cycles?
Something like:
```
datasets:
  - name: experiment
    type: IodaObsSpace
    filenames:
    - ./PT6H/2021-07-08/ncdiag.fgat_jra55_01.ob.PT6H.sst_viirs_n20_l3u.2021-07-08T03:00:00Z.nc4
    - ./PT6H/2021-07-08/ncdiag.fgat_jra55_01.ob.PT6H.sst_viirs_n20_l3u.2021-07-08T09:00:00Z.nc4
    - ./PT6H/2021-07-08/ncdiag.fgat_jra55_01.ob.PT6H.sst_viirs_n20_l3u.2021-07-08T15:00:00Z.nc4
    - ./PT6H/2021-07-08/ncdiag.fgat_jra55_01.ob.PT6H.sst_viirs_n20_l3u.2021-07-08T21:00:00Z.nc4
```
